# Generated by Django 5.0.6 on 2024-06-07 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='description',
            field=models.TextField(max_length=150, verbose_name='Описание датчика'),
        ),
    ]
